#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun May 17 12:28:08 BST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b99bdc1c0fac4517be70b2f6bf40135d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tpg_tb_behav xil_defaultlib.tpg_tb -log elaborate.log"
xelab -wto b99bdc1c0fac4517be70b2f6bf40135d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tpg_tb_behav xil_defaultlib.tpg_tb -log elaborate.log

